name: Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "12 5 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install ArxivFeed
        shell: bash
        run: cargo install --git https://github.com/NotCraft/ArxivFeed --rev 666803907c51655b22dd541ef2cdc11e21309def --locked arxivfeed
      - name: Build rss
        run: ~/.cargo/bin/arxivfeed
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          force_orphan: true
